# Generated by Django 3.2.5 on 2021-08-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_doctorappointment_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
