# Generated by Django 3.2.5 on 2021-08-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctorappointment_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
