# Generated by Django 3.2.5 on 2021-08-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_doctorappointment_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutpatientCoordinator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('token_no', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
