# Generated by Django 3.2.5 on 2021-08-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_outpatientcoordinator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opcoordinator',
            name='address',
        ),
        migrations.RemoveField(
            model_name='opcoordinator',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='opcoordinator',
            name='name',
        ),
    ]
