# Generated by Django 3.2.5 on 2021-08-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210805_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpCoordinator',
        ),
    ]
