# Generated by Django 3.2.5 on 2021-08-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_token'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Token',
            new_name='OPToken',
        ),
    ]
