# Generated by Django 3.2.5 on 2021-08-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_token_optoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPTokenStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_token_no', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='outpatientcoordinator',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.optokenstatus'),
            preserve_default=False,
        ),
    ]
