# Generated by Django 3.2.5 on 2021-08-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210807_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpatientcoordinator',
            name='token_no',
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(default='2001-07-21'),
            preserve_default=False,
        ),
    ]
