# Generated by Django 3.2.5 on 2021-08-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210807_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='optoken',
            name='is_verified',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
