# Generated by Django 3.2.5 on 2021-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210812_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='adhaar_no',
            field=models.CharField(max_length=12),
        ),
    ]
