# Generated by Django 3.2.5 on 2021-08-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_patient_adhaar_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
